### ISSUE TITLE
Nextcloud Desktop no longer have access to KDE wallet

### ISSUE THREAD

**Issue by Szwendacz99** [flathub/com.nextcloud.desktopclient.nextcloud#125]
Since latest changes in the repo, the app cannot use KDE wallet, and is asking for authorization via web browser each time it starts.

**Comment by Croydon** [comment]
I can confirm this problem on Fedora 38 + KDE, though I have no idea personally what the cause is.

**Comment by Szwendacz99** [comment]
I don

> I can confirm this problem on Fedora 38 + KDE, though I have no idea personally what the cause is.
> 
> Edit: Duplicate of #76

I don't think this is a duplicate, check the test build from my pull request, it fixes the problem for me.

**Comment by marvin-te** [comment]
Can comfirm. Nextcloud asked for the password on my freshly installed KDE machine every time. After enabling the kwallet bus via `override` it finally works.
And now the login data is visibly stored in KWallet as well.

Instant fix:
```
flatpak --user override --talk-name=org.kde.kwalletd5 com.nextcloud.desktopclient.nextcloud
```

The PR by @Szwendacz99 from my understanding does the exact same thing, just baking it into the flatpak instead of needing a per-user override.

**Comment by melroy89** [comment]
Today (using 1.14.1) Nextcloud app is forcing me to create a wallet? This is no crypto scam right?
